// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_msgs.TFMessage.proto

#ifndef PROTOBUF_proto_5fmsgs_2eTFMessage_2eproto__INCLUDED
#define PROTOBUF_proto_5fmsgs_2eTFMessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace proto_msg {
class TF;
class TFDefaultTypeInternal;
extern TFDefaultTypeInternal _TF_default_instance_;
class TFMessage;
class TFMessageDefaultTypeInternal;
extern TFMessageDefaultTypeInternal _TFMessage_default_instance_;
class TFStaticMessage;
class TFStaticMessageDefaultTypeInternal;
extern TFStaticMessageDefaultTypeInternal _TFStaticMessage_default_instance_;
}  // namespace proto_msg

namespace proto_msg {

namespace protobuf_proto_5fmsgs_2eTFMessage_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_proto_5fmsgs_2eTFMessage_2eproto

// ===================================================================

class TF : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto_msg.TF) */ {
 public:
  TF();
  virtual ~TF();

  TF(const TF& from);

  inline TF& operator=(const TF& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TF(TF&& from) noexcept
    : TF() {
    *this = ::std::move(from);
  }

  inline TF& operator=(TF&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TF& default_instance();

  static inline const TF* internal_default_instance() {
    return reinterpret_cast<const TF*>(
               &_TF_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(TF* other);
  friend void swap(TF& a, TF& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TF* New() const PROTOBUF_FINAL { return New(NULL); }

  TF* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TF& from);
  void MergeFrom(const TF& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TF* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string frame_id = 3;
  bool has_frame_id() const;
  void clear_frame_id();
  static const int kFrameIdFieldNumber = 3;
  const ::std::string& frame_id() const;
  void set_frame_id(const ::std::string& value);
  #if LANG_CXX11
  void set_frame_id(::std::string&& value);
  #endif
  void set_frame_id(const char* value);
  void set_frame_id(const char* value, size_t size);
  ::std::string* mutable_frame_id();
  ::std::string* release_frame_id();
  void set_allocated_frame_id(::std::string* frame_id);

  // required string child_frame_id = 4;
  bool has_child_frame_id() const;
  void clear_child_frame_id();
  static const int kChildFrameIdFieldNumber = 4;
  const ::std::string& child_frame_id() const;
  void set_child_frame_id(const ::std::string& value);
  #if LANG_CXX11
  void set_child_frame_id(::std::string&& value);
  #endif
  void set_child_frame_id(const char* value);
  void set_child_frame_id(const char* value, size_t size);
  ::std::string* mutable_child_frame_id();
  ::std::string* release_child_frame_id();
  void set_allocated_child_frame_id(::std::string* child_frame_id);

  // required double publish_stamp = 2;
  bool has_publish_stamp() const;
  void clear_publish_stamp();
  static const int kPublishStampFieldNumber = 2;
  double publish_stamp() const;
  void set_publish_stamp(double value);

  // required double x = 5;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 5;
  double x() const;
  void set_x(double value);

  // required double y = 6;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 6;
  double y() const;
  void set_y(double value);

  // required double z = 7;
  bool has_z() const;
  void clear_z();
  static const int kZFieldNumber = 7;
  double z() const;
  void set_z(double value);

  // required double roll = 8;
  bool has_roll() const;
  void clear_roll();
  static const int kRollFieldNumber = 8;
  double roll() const;
  void set_roll(double value);

  // required double pitch = 9;
  bool has_pitch() const;
  void clear_pitch();
  static const int kPitchFieldNumber = 9;
  double pitch() const;
  void set_pitch(double value);

  // required double yaw = 10;
  bool has_yaw() const;
  void clear_yaw();
  static const int kYawFieldNumber = 10;
  double yaw() const;
  void set_yaw(double value);

  // @@protoc_insertion_point(class_scope:proto_msg.TF)
 private:
  void set_has_publish_stamp();
  void clear_has_publish_stamp();
  void set_has_frame_id();
  void clear_has_frame_id();
  void set_has_child_frame_id();
  void clear_has_child_frame_id();
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();
  void set_has_z();
  void clear_has_z();
  void set_has_roll();
  void clear_has_roll();
  void set_has_pitch();
  void clear_has_pitch();
  void set_has_yaw();
  void clear_has_yaw();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr frame_id_;
  ::google::protobuf::internal::ArenaStringPtr child_frame_id_;
  double publish_stamp_;
  double x_;
  double y_;
  double z_;
  double roll_;
  double pitch_;
  double yaw_;
  friend struct protobuf_proto_5fmsgs_2eTFMessage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TFMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto_msg.TFMessage) */ {
 public:
  TFMessage();
  virtual ~TFMessage();

  TFMessage(const TFMessage& from);

  inline TFMessage& operator=(const TFMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TFMessage(TFMessage&& from) noexcept
    : TFMessage() {
    *this = ::std::move(from);
  }

  inline TFMessage& operator=(TFMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TFMessage& default_instance();

  static inline const TFMessage* internal_default_instance() {
    return reinterpret_cast<const TFMessage*>(
               &_TFMessage_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(TFMessage* other);
  friend void swap(TFMessage& a, TFMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TFMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  TFMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TFMessage& from);
  void MergeFrom(const TFMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TFMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .proto_msg.TF tfs = 2;
  int tfs_size() const;
  void clear_tfs();
  static const int kTfsFieldNumber = 2;
  const ::proto_msg::TF& tfs(int index) const;
  ::proto_msg::TF* mutable_tfs(int index);
  ::proto_msg::TF* add_tfs();
  ::google::protobuf::RepeatedPtrField< ::proto_msg::TF >*
      mutable_tfs();
  const ::google::protobuf::RepeatedPtrField< ::proto_msg::TF >&
      tfs() const;

  // required string protocol_type = 1;
  bool has_protocol_type() const;
  void clear_protocol_type();
  static const int kProtocolTypeFieldNumber = 1;
  const ::std::string& protocol_type() const;
  void set_protocol_type(const ::std::string& value);
  #if LANG_CXX11
  void set_protocol_type(::std::string&& value);
  #endif
  void set_protocol_type(const char* value);
  void set_protocol_type(const char* value, size_t size);
  ::std::string* mutable_protocol_type();
  ::std::string* release_protocol_type();
  void set_allocated_protocol_type(::std::string* protocol_type);

  // @@protoc_insertion_point(class_scope:proto_msg.TFMessage)
 private:
  void set_has_protocol_type();
  void clear_has_protocol_type();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::proto_msg::TF > tfs_;
  ::google::protobuf::internal::ArenaStringPtr protocol_type_;
  friend struct protobuf_proto_5fmsgs_2eTFMessage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TFStaticMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto_msg.TFStaticMessage) */ {
 public:
  TFStaticMessage();
  virtual ~TFStaticMessage();

  TFStaticMessage(const TFStaticMessage& from);

  inline TFStaticMessage& operator=(const TFStaticMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TFStaticMessage(TFStaticMessage&& from) noexcept
    : TFStaticMessage() {
    *this = ::std::move(from);
  }

  inline TFStaticMessage& operator=(TFStaticMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TFStaticMessage& default_instance();

  static inline const TFStaticMessage* internal_default_instance() {
    return reinterpret_cast<const TFStaticMessage*>(
               &_TFStaticMessage_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(TFStaticMessage* other);
  friend void swap(TFStaticMessage& a, TFStaticMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TFStaticMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  TFStaticMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TFStaticMessage& from);
  void MergeFrom(const TFStaticMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TFStaticMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .proto_msg.TF tfs = 2;
  int tfs_size() const;
  void clear_tfs();
  static const int kTfsFieldNumber = 2;
  const ::proto_msg::TF& tfs(int index) const;
  ::proto_msg::TF* mutable_tfs(int index);
  ::proto_msg::TF* add_tfs();
  ::google::protobuf::RepeatedPtrField< ::proto_msg::TF >*
      mutable_tfs();
  const ::google::protobuf::RepeatedPtrField< ::proto_msg::TF >&
      tfs() const;

  // required string protocol_type = 1;
  bool has_protocol_type() const;
  void clear_protocol_type();
  static const int kProtocolTypeFieldNumber = 1;
  const ::std::string& protocol_type() const;
  void set_protocol_type(const ::std::string& value);
  #if LANG_CXX11
  void set_protocol_type(::std::string&& value);
  #endif
  void set_protocol_type(const char* value);
  void set_protocol_type(const char* value, size_t size);
  ::std::string* mutable_protocol_type();
  ::std::string* release_protocol_type();
  void set_allocated_protocol_type(::std::string* protocol_type);

  // @@protoc_insertion_point(class_scope:proto_msg.TFStaticMessage)
 private:
  void set_has_protocol_type();
  void clear_has_protocol_type();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::proto_msg::TF > tfs_;
  ::google::protobuf::internal::ArenaStringPtr protocol_type_;
  friend struct protobuf_proto_5fmsgs_2eTFMessage_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TF

// required double publish_stamp = 2;
inline bool TF::has_publish_stamp() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TF::set_has_publish_stamp() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TF::clear_has_publish_stamp() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TF::clear_publish_stamp() {
  publish_stamp_ = 0;
  clear_has_publish_stamp();
}
inline double TF::publish_stamp() const {
  // @@protoc_insertion_point(field_get:proto_msg.TF.publish_stamp)
  return publish_stamp_;
}
inline void TF::set_publish_stamp(double value) {
  set_has_publish_stamp();
  publish_stamp_ = value;
  // @@protoc_insertion_point(field_set:proto_msg.TF.publish_stamp)
}

// required string frame_id = 3;
inline bool TF::has_frame_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TF::set_has_frame_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TF::clear_has_frame_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TF::clear_frame_id() {
  frame_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_frame_id();
}
inline const ::std::string& TF::frame_id() const {
  // @@protoc_insertion_point(field_get:proto_msg.TF.frame_id)
  return frame_id_.GetNoArena();
}
inline void TF::set_frame_id(const ::std::string& value) {
  set_has_frame_id();
  frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto_msg.TF.frame_id)
}
#if LANG_CXX11
inline void TF::set_frame_id(::std::string&& value) {
  set_has_frame_id();
  frame_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto_msg.TF.frame_id)
}
#endif
inline void TF::set_frame_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_frame_id();
  frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto_msg.TF.frame_id)
}
inline void TF::set_frame_id(const char* value, size_t size) {
  set_has_frame_id();
  frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto_msg.TF.frame_id)
}
inline ::std::string* TF::mutable_frame_id() {
  set_has_frame_id();
  // @@protoc_insertion_point(field_mutable:proto_msg.TF.frame_id)
  return frame_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TF::release_frame_id() {
  // @@protoc_insertion_point(field_release:proto_msg.TF.frame_id)
  clear_has_frame_id();
  return frame_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TF::set_allocated_frame_id(::std::string* frame_id) {
  if (frame_id != NULL) {
    set_has_frame_id();
  } else {
    clear_has_frame_id();
  }
  frame_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), frame_id);
  // @@protoc_insertion_point(field_set_allocated:proto_msg.TF.frame_id)
}

// required string child_frame_id = 4;
inline bool TF::has_child_frame_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TF::set_has_child_frame_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TF::clear_has_child_frame_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TF::clear_child_frame_id() {
  child_frame_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_child_frame_id();
}
inline const ::std::string& TF::child_frame_id() const {
  // @@protoc_insertion_point(field_get:proto_msg.TF.child_frame_id)
  return child_frame_id_.GetNoArena();
}
inline void TF::set_child_frame_id(const ::std::string& value) {
  set_has_child_frame_id();
  child_frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto_msg.TF.child_frame_id)
}
#if LANG_CXX11
inline void TF::set_child_frame_id(::std::string&& value) {
  set_has_child_frame_id();
  child_frame_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto_msg.TF.child_frame_id)
}
#endif
inline void TF::set_child_frame_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_child_frame_id();
  child_frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto_msg.TF.child_frame_id)
}
inline void TF::set_child_frame_id(const char* value, size_t size) {
  set_has_child_frame_id();
  child_frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto_msg.TF.child_frame_id)
}
inline ::std::string* TF::mutable_child_frame_id() {
  set_has_child_frame_id();
  // @@protoc_insertion_point(field_mutable:proto_msg.TF.child_frame_id)
  return child_frame_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TF::release_child_frame_id() {
  // @@protoc_insertion_point(field_release:proto_msg.TF.child_frame_id)
  clear_has_child_frame_id();
  return child_frame_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TF::set_allocated_child_frame_id(::std::string* child_frame_id) {
  if (child_frame_id != NULL) {
    set_has_child_frame_id();
  } else {
    clear_has_child_frame_id();
  }
  child_frame_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), child_frame_id);
  // @@protoc_insertion_point(field_set_allocated:proto_msg.TF.child_frame_id)
}

// required double x = 5;
inline bool TF::has_x() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void TF::set_has_x() {
  _has_bits_[0] |= 0x00000008u;
}
inline void TF::clear_has_x() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void TF::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline double TF::x() const {
  // @@protoc_insertion_point(field_get:proto_msg.TF.x)
  return x_;
}
inline void TF::set_x(double value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:proto_msg.TF.x)
}

// required double y = 6;
inline bool TF::has_y() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void TF::set_has_y() {
  _has_bits_[0] |= 0x00000010u;
}
inline void TF::clear_has_y() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void TF::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double TF::y() const {
  // @@protoc_insertion_point(field_get:proto_msg.TF.y)
  return y_;
}
inline void TF::set_y(double value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:proto_msg.TF.y)
}

// required double z = 7;
inline bool TF::has_z() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void TF::set_has_z() {
  _has_bits_[0] |= 0x00000020u;
}
inline void TF::clear_has_z() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void TF::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline double TF::z() const {
  // @@protoc_insertion_point(field_get:proto_msg.TF.z)
  return z_;
}
inline void TF::set_z(double value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:proto_msg.TF.z)
}

// required double roll = 8;
inline bool TF::has_roll() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void TF::set_has_roll() {
  _has_bits_[0] |= 0x00000040u;
}
inline void TF::clear_has_roll() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void TF::clear_roll() {
  roll_ = 0;
  clear_has_roll();
}
inline double TF::roll() const {
  // @@protoc_insertion_point(field_get:proto_msg.TF.roll)
  return roll_;
}
inline void TF::set_roll(double value) {
  set_has_roll();
  roll_ = value;
  // @@protoc_insertion_point(field_set:proto_msg.TF.roll)
}

// required double pitch = 9;
inline bool TF::has_pitch() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void TF::set_has_pitch() {
  _has_bits_[0] |= 0x00000080u;
}
inline void TF::clear_has_pitch() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void TF::clear_pitch() {
  pitch_ = 0;
  clear_has_pitch();
}
inline double TF::pitch() const {
  // @@protoc_insertion_point(field_get:proto_msg.TF.pitch)
  return pitch_;
}
inline void TF::set_pitch(double value) {
  set_has_pitch();
  pitch_ = value;
  // @@protoc_insertion_point(field_set:proto_msg.TF.pitch)
}

// required double yaw = 10;
inline bool TF::has_yaw() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void TF::set_has_yaw() {
  _has_bits_[0] |= 0x00000100u;
}
inline void TF::clear_has_yaw() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void TF::clear_yaw() {
  yaw_ = 0;
  clear_has_yaw();
}
inline double TF::yaw() const {
  // @@protoc_insertion_point(field_get:proto_msg.TF.yaw)
  return yaw_;
}
inline void TF::set_yaw(double value) {
  set_has_yaw();
  yaw_ = value;
  // @@protoc_insertion_point(field_set:proto_msg.TF.yaw)
}

// -------------------------------------------------------------------

// TFMessage

// required string protocol_type = 1;
inline bool TFMessage::has_protocol_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TFMessage::set_has_protocol_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TFMessage::clear_has_protocol_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TFMessage::clear_protocol_type() {
  protocol_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_protocol_type();
}
inline const ::std::string& TFMessage::protocol_type() const {
  // @@protoc_insertion_point(field_get:proto_msg.TFMessage.protocol_type)
  return protocol_type_.GetNoArena();
}
inline void TFMessage::set_protocol_type(const ::std::string& value) {
  set_has_protocol_type();
  protocol_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto_msg.TFMessage.protocol_type)
}
#if LANG_CXX11
inline void TFMessage::set_protocol_type(::std::string&& value) {
  set_has_protocol_type();
  protocol_type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto_msg.TFMessage.protocol_type)
}
#endif
inline void TFMessage::set_protocol_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_protocol_type();
  protocol_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto_msg.TFMessage.protocol_type)
}
inline void TFMessage::set_protocol_type(const char* value, size_t size) {
  set_has_protocol_type();
  protocol_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto_msg.TFMessage.protocol_type)
}
inline ::std::string* TFMessage::mutable_protocol_type() {
  set_has_protocol_type();
  // @@protoc_insertion_point(field_mutable:proto_msg.TFMessage.protocol_type)
  return protocol_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TFMessage::release_protocol_type() {
  // @@protoc_insertion_point(field_release:proto_msg.TFMessage.protocol_type)
  clear_has_protocol_type();
  return protocol_type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TFMessage::set_allocated_protocol_type(::std::string* protocol_type) {
  if (protocol_type != NULL) {
    set_has_protocol_type();
  } else {
    clear_has_protocol_type();
  }
  protocol_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), protocol_type);
  // @@protoc_insertion_point(field_set_allocated:proto_msg.TFMessage.protocol_type)
}

// repeated .proto_msg.TF tfs = 2;
inline int TFMessage::tfs_size() const {
  return tfs_.size();
}
inline void TFMessage::clear_tfs() {
  tfs_.Clear();
}
inline const ::proto_msg::TF& TFMessage::tfs(int index) const {
  // @@protoc_insertion_point(field_get:proto_msg.TFMessage.tfs)
  return tfs_.Get(index);
}
inline ::proto_msg::TF* TFMessage::mutable_tfs(int index) {
  // @@protoc_insertion_point(field_mutable:proto_msg.TFMessage.tfs)
  return tfs_.Mutable(index);
}
inline ::proto_msg::TF* TFMessage::add_tfs() {
  // @@protoc_insertion_point(field_add:proto_msg.TFMessage.tfs)
  return tfs_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::proto_msg::TF >*
TFMessage::mutable_tfs() {
  // @@protoc_insertion_point(field_mutable_list:proto_msg.TFMessage.tfs)
  return &tfs_;
}
inline const ::google::protobuf::RepeatedPtrField< ::proto_msg::TF >&
TFMessage::tfs() const {
  // @@protoc_insertion_point(field_list:proto_msg.TFMessage.tfs)
  return tfs_;
}

// -------------------------------------------------------------------

// TFStaticMessage

// required string protocol_type = 1;
inline bool TFStaticMessage::has_protocol_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TFStaticMessage::set_has_protocol_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TFStaticMessage::clear_has_protocol_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TFStaticMessage::clear_protocol_type() {
  protocol_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_protocol_type();
}
inline const ::std::string& TFStaticMessage::protocol_type() const {
  // @@protoc_insertion_point(field_get:proto_msg.TFStaticMessage.protocol_type)
  return protocol_type_.GetNoArena();
}
inline void TFStaticMessage::set_protocol_type(const ::std::string& value) {
  set_has_protocol_type();
  protocol_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto_msg.TFStaticMessage.protocol_type)
}
#if LANG_CXX11
inline void TFStaticMessage::set_protocol_type(::std::string&& value) {
  set_has_protocol_type();
  protocol_type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto_msg.TFStaticMessage.protocol_type)
}
#endif
inline void TFStaticMessage::set_protocol_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_protocol_type();
  protocol_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto_msg.TFStaticMessage.protocol_type)
}
inline void TFStaticMessage::set_protocol_type(const char* value, size_t size) {
  set_has_protocol_type();
  protocol_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto_msg.TFStaticMessage.protocol_type)
}
inline ::std::string* TFStaticMessage::mutable_protocol_type() {
  set_has_protocol_type();
  // @@protoc_insertion_point(field_mutable:proto_msg.TFStaticMessage.protocol_type)
  return protocol_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TFStaticMessage::release_protocol_type() {
  // @@protoc_insertion_point(field_release:proto_msg.TFStaticMessage.protocol_type)
  clear_has_protocol_type();
  return protocol_type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TFStaticMessage::set_allocated_protocol_type(::std::string* protocol_type) {
  if (protocol_type != NULL) {
    set_has_protocol_type();
  } else {
    clear_has_protocol_type();
  }
  protocol_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), protocol_type);
  // @@protoc_insertion_point(field_set_allocated:proto_msg.TFStaticMessage.protocol_type)
}

// repeated .proto_msg.TF tfs = 2;
inline int TFStaticMessage::tfs_size() const {
  return tfs_.size();
}
inline void TFStaticMessage::clear_tfs() {
  tfs_.Clear();
}
inline const ::proto_msg::TF& TFStaticMessage::tfs(int index) const {
  // @@protoc_insertion_point(field_get:proto_msg.TFStaticMessage.tfs)
  return tfs_.Get(index);
}
inline ::proto_msg::TF* TFStaticMessage::mutable_tfs(int index) {
  // @@protoc_insertion_point(field_mutable:proto_msg.TFStaticMessage.tfs)
  return tfs_.Mutable(index);
}
inline ::proto_msg::TF* TFStaticMessage::add_tfs() {
  // @@protoc_insertion_point(field_add:proto_msg.TFStaticMessage.tfs)
  return tfs_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::proto_msg::TF >*
TFStaticMessage::mutable_tfs() {
  // @@protoc_insertion_point(field_mutable_list:proto_msg.TFStaticMessage.tfs)
  return &tfs_;
}
inline const ::google::protobuf::RepeatedPtrField< ::proto_msg::TF >&
TFStaticMessage::tfs() const {
  // @@protoc_insertion_point(field_list:proto_msg.TFStaticMessage.tfs)
  return tfs_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace proto_msg

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_5fmsgs_2eTFMessage_2eproto__INCLUDED
