// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_msgs.OccupancyGrid.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "proto_msgs.OccupancyGrid.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace proto_msg {
class OccupancyGridDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<OccupancyGrid>
     _instance;
} _OccupancyGrid_default_instance_;

namespace protobuf_proto_5fmsgs_2eOccupancyGrid_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OccupancyGrid, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OccupancyGrid, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OccupancyGrid, protocol_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OccupancyGrid, publish_stamp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OccupancyGrid, load_time_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OccupancyGrid, frame_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OccupancyGrid, resolution_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OccupancyGrid, width_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OccupancyGrid, height_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OccupancyGrid, x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OccupancyGrid, y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OccupancyGrid, z_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OccupancyGrid, q_x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OccupancyGrid, q_y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OccupancyGrid, q_z_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OccupancyGrid, q_w_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OccupancyGrid, map_data_),
  0,
  3,
  4,
  1,
  5,
  6,
  14,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  2,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 20, sizeof(OccupancyGrid)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_OccupancyGrid_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "proto_msgs.OccupancyGrid.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _OccupancyGrid_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_OccupancyGrid_default_instance_);}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\036proto_msgs.OccupancyGrid.proto\022\tproto_"
      "msg\"\374\001\n\rOccupancyGrid\022\025\n\rprotocol_type\030\001"
      " \002(\t\022\025\n\rpublish_stamp\030\002 \002(\001\022\021\n\tload_time"
      "\030\003 \002(\001\022\020\n\010frame_id\030\004 \002(\t\022\022\n\nresolution\030\005"
      " \002(\002\022\r\n\005width\030\006 \002(\002\022\016\n\006height\030\007 \002(\002\022\t\n\001x"
      "\030\010 \002(\001\022\t\n\001y\030\t \002(\001\022\t\n\001z\030\n \002(\001\022\013\n\003q_x\030\013 \002("
      "\001\022\013\n\003q_y\030\014 \002(\001\022\013\n\003q_z\030\r \002(\001\022\013\n\003q_w\030\016 \002(\001"
      "\022\020\n\010map_data\030\017 \002(\014"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 298);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "proto_msgs.OccupancyGrid.proto", &protobuf_RegisterTypes);
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_proto_5fmsgs_2eOccupancyGrid_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int OccupancyGrid::kProtocolTypeFieldNumber;
const int OccupancyGrid::kPublishStampFieldNumber;
const int OccupancyGrid::kLoadTimeFieldNumber;
const int OccupancyGrid::kFrameIdFieldNumber;
const int OccupancyGrid::kResolutionFieldNumber;
const int OccupancyGrid::kWidthFieldNumber;
const int OccupancyGrid::kHeightFieldNumber;
const int OccupancyGrid::kXFieldNumber;
const int OccupancyGrid::kYFieldNumber;
const int OccupancyGrid::kZFieldNumber;
const int OccupancyGrid::kQXFieldNumber;
const int OccupancyGrid::kQYFieldNumber;
const int OccupancyGrid::kQZFieldNumber;
const int OccupancyGrid::kQWFieldNumber;
const int OccupancyGrid::kMapDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

OccupancyGrid::OccupancyGrid()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_proto_5fmsgs_2eOccupancyGrid_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto_msg.OccupancyGrid)
}
OccupancyGrid::OccupancyGrid(const OccupancyGrid& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  protocol_type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_protocol_type()) {
    protocol_type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.protocol_type_);
  }
  frame_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_frame_id()) {
    frame_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.frame_id_);
  }
  map_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_map_data()) {
    map_data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.map_data_);
  }
  ::memcpy(&publish_stamp_, &from.publish_stamp_,
    static_cast<size_t>(reinterpret_cast<char*>(&height_) -
    reinterpret_cast<char*>(&publish_stamp_)) + sizeof(height_));
  // @@protoc_insertion_point(copy_constructor:proto_msg.OccupancyGrid)
}

void OccupancyGrid::SharedCtor() {
  _cached_size_ = 0;
  protocol_type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  frame_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  map_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&publish_stamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&height_) -
      reinterpret_cast<char*>(&publish_stamp_)) + sizeof(height_));
}

OccupancyGrid::~OccupancyGrid() {
  // @@protoc_insertion_point(destructor:proto_msg.OccupancyGrid)
  SharedDtor();
}

void OccupancyGrid::SharedDtor() {
  protocol_type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  frame_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  map_data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void OccupancyGrid::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* OccupancyGrid::descriptor() {
  protobuf_proto_5fmsgs_2eOccupancyGrid_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto_5fmsgs_2eOccupancyGrid_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const OccupancyGrid& OccupancyGrid::default_instance() {
  protobuf_proto_5fmsgs_2eOccupancyGrid_2eproto::InitDefaults();
  return *internal_default_instance();
}

OccupancyGrid* OccupancyGrid::New(::google::protobuf::Arena* arena) const {
  OccupancyGrid* n = new OccupancyGrid;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void OccupancyGrid::Clear() {
// @@protoc_insertion_point(message_clear_start:proto_msg.OccupancyGrid)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 7u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(!protocol_type_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*protocol_type_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(!frame_id_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*frame_id_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(!map_data_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*map_data_.UnsafeRawStringPointer())->clear();
    }
  }
  if (cached_has_bits & 248u) {
    ::memset(&publish_stamp_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&x_) -
        reinterpret_cast<char*>(&publish_stamp_)) + sizeof(x_));
  }
  if (cached_has_bits & 32512u) {
    ::memset(&y_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&height_) -
        reinterpret_cast<char*>(&y_)) + sizeof(height_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool OccupancyGrid::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto_msg.OccupancyGrid)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string protocol_type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_protocol_type()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->protocol_type().data(), static_cast<int>(this->protocol_type().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "proto_msg.OccupancyGrid.protocol_type");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required double publish_stamp = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {
          set_has_publish_stamp();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &publish_stamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required double load_time = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u /* 25 & 0xFF */)) {
          set_has_load_time();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &load_time_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string frame_id = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_frame_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->frame_id().data(), static_cast<int>(this->frame_id().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "proto_msg.OccupancyGrid.frame_id");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required float resolution = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(45u /* 45 & 0xFF */)) {
          set_has_resolution();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &resolution_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required float width = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(53u /* 53 & 0xFF */)) {
          set_has_width();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &width_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required float height = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(61u /* 61 & 0xFF */)) {
          set_has_height();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &height_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required double x = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(65u /* 65 & 0xFF */)) {
          set_has_x();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required double y = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(73u /* 73 & 0xFF */)) {
          set_has_y();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required double z = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(81u /* 81 & 0xFF */)) {
          set_has_z();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &z_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required double q_x = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(89u /* 89 & 0xFF */)) {
          set_has_q_x();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &q_x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required double q_y = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(97u /* 97 & 0xFF */)) {
          set_has_q_y();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &q_y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required double q_z = 13;
      case 13: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(105u /* 105 & 0xFF */)) {
          set_has_q_z();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &q_z_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required double q_w = 14;
      case 14: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(113u /* 113 & 0xFF */)) {
          set_has_q_w();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &q_w_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required bytes map_data = 15;
      case 15: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(122u /* 122 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_map_data()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto_msg.OccupancyGrid)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto_msg.OccupancyGrid)
  return false;
#undef DO_
}

void OccupancyGrid::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto_msg.OccupancyGrid)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string protocol_type = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->protocol_type().data(), static_cast<int>(this->protocol_type().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "proto_msg.OccupancyGrid.protocol_type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->protocol_type(), output);
  }

  // required double publish_stamp = 2;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->publish_stamp(), output);
  }

  // required double load_time = 3;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->load_time(), output);
  }

  // required string frame_id = 4;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->frame_id().data(), static_cast<int>(this->frame_id().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "proto_msg.OccupancyGrid.frame_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->frame_id(), output);
  }

  // required float resolution = 5;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(5, this->resolution(), output);
  }

  // required float width = 6;
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(6, this->width(), output);
  }

  // required float height = 7;
  if (cached_has_bits & 0x00004000u) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(7, this->height(), output);
  }

  // required double x = 8;
  if (cached_has_bits & 0x00000080u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(8, this->x(), output);
  }

  // required double y = 9;
  if (cached_has_bits & 0x00000100u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(9, this->y(), output);
  }

  // required double z = 10;
  if (cached_has_bits & 0x00000200u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(10, this->z(), output);
  }

  // required double q_x = 11;
  if (cached_has_bits & 0x00000400u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(11, this->q_x(), output);
  }

  // required double q_y = 12;
  if (cached_has_bits & 0x00000800u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(12, this->q_y(), output);
  }

  // required double q_z = 13;
  if (cached_has_bits & 0x00001000u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(13, this->q_z(), output);
  }

  // required double q_w = 14;
  if (cached_has_bits & 0x00002000u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(14, this->q_w(), output);
  }

  // required bytes map_data = 15;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      15, this->map_data(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:proto_msg.OccupancyGrid)
}

::google::protobuf::uint8* OccupancyGrid::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:proto_msg.OccupancyGrid)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string protocol_type = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->protocol_type().data(), static_cast<int>(this->protocol_type().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "proto_msg.OccupancyGrid.protocol_type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->protocol_type(), target);
  }

  // required double publish_stamp = 2;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->publish_stamp(), target);
  }

  // required double load_time = 3;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->load_time(), target);
  }

  // required string frame_id = 4;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->frame_id().data(), static_cast<int>(this->frame_id().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "proto_msg.OccupancyGrid.frame_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->frame_id(), target);
  }

  // required float resolution = 5;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(5, this->resolution(), target);
  }

  // required float width = 6;
  if (cached_has_bits & 0x00000040u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(6, this->width(), target);
  }

  // required float height = 7;
  if (cached_has_bits & 0x00004000u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(7, this->height(), target);
  }

  // required double x = 8;
  if (cached_has_bits & 0x00000080u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(8, this->x(), target);
  }

  // required double y = 9;
  if (cached_has_bits & 0x00000100u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(9, this->y(), target);
  }

  // required double z = 10;
  if (cached_has_bits & 0x00000200u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(10, this->z(), target);
  }

  // required double q_x = 11;
  if (cached_has_bits & 0x00000400u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(11, this->q_x(), target);
  }

  // required double q_y = 12;
  if (cached_has_bits & 0x00000800u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(12, this->q_y(), target);
  }

  // required double q_z = 13;
  if (cached_has_bits & 0x00001000u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(13, this->q_z(), target);
  }

  // required double q_w = 14;
  if (cached_has_bits & 0x00002000u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(14, this->q_w(), target);
  }

  // required bytes map_data = 15;
  if (cached_has_bits & 0x00000004u) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        15, this->map_data(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto_msg.OccupancyGrid)
  return target;
}

size_t OccupancyGrid::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:proto_msg.OccupancyGrid)
  size_t total_size = 0;

  if (has_protocol_type()) {
    // required string protocol_type = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->protocol_type());
  }

  if (has_frame_id()) {
    // required string frame_id = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->frame_id());
  }

  if (has_map_data()) {
    // required bytes map_data = 15;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->map_data());
  }

  if (has_publish_stamp()) {
    // required double publish_stamp = 2;
    total_size += 1 + 8;
  }

  if (has_load_time()) {
    // required double load_time = 3;
    total_size += 1 + 8;
  }

  if (has_resolution()) {
    // required float resolution = 5;
    total_size += 1 + 4;
  }

  if (has_width()) {
    // required float width = 6;
    total_size += 1 + 4;
  }

  if (has_x()) {
    // required double x = 8;
    total_size += 1 + 8;
  }

  if (has_y()) {
    // required double y = 9;
    total_size += 1 + 8;
  }

  if (has_z()) {
    // required double z = 10;
    total_size += 1 + 8;
  }

  if (has_q_x()) {
    // required double q_x = 11;
    total_size += 1 + 8;
  }

  if (has_q_y()) {
    // required double q_y = 12;
    total_size += 1 + 8;
  }

  if (has_q_z()) {
    // required double q_z = 13;
    total_size += 1 + 8;
  }

  if (has_q_w()) {
    // required double q_w = 14;
    total_size += 1 + 8;
  }

  if (has_height()) {
    // required float height = 7;
    total_size += 1 + 4;
  }

  return total_size;
}
size_t OccupancyGrid::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto_msg.OccupancyGrid)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x00007fff) ^ 0x00007fff) == 0) {  // All required fields are present.
    // required string protocol_type = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->protocol_type());

    // required string frame_id = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->frame_id());

    // required bytes map_data = 15;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->map_data());

    // required double publish_stamp = 2;
    total_size += 1 + 8;

    // required double load_time = 3;
    total_size += 1 + 8;

    // required float resolution = 5;
    total_size += 1 + 4;

    // required float width = 6;
    total_size += 1 + 4;

    // required double x = 8;
    total_size += 1 + 8;

    // required double y = 9;
    total_size += 1 + 8;

    // required double z = 10;
    total_size += 1 + 8;

    // required double q_x = 11;
    total_size += 1 + 8;

    // required double q_y = 12;
    total_size += 1 + 8;

    // required double q_z = 13;
    total_size += 1 + 8;

    // required double q_w = 14;
    total_size += 1 + 8;

    // required float height = 7;
    total_size += 1 + 4;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void OccupancyGrid::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto_msg.OccupancyGrid)
  GOOGLE_DCHECK_NE(&from, this);
  const OccupancyGrid* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const OccupancyGrid>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto_msg.OccupancyGrid)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto_msg.OccupancyGrid)
    MergeFrom(*source);
  }
}

void OccupancyGrid::MergeFrom(const OccupancyGrid& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto_msg.OccupancyGrid)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 255u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_protocol_type();
      protocol_type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.protocol_type_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_frame_id();
      frame_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.frame_id_);
    }
    if (cached_has_bits & 0x00000004u) {
      set_has_map_data();
      map_data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.map_data_);
    }
    if (cached_has_bits & 0x00000008u) {
      publish_stamp_ = from.publish_stamp_;
    }
    if (cached_has_bits & 0x00000010u) {
      load_time_ = from.load_time_;
    }
    if (cached_has_bits & 0x00000020u) {
      resolution_ = from.resolution_;
    }
    if (cached_has_bits & 0x00000040u) {
      width_ = from.width_;
    }
    if (cached_has_bits & 0x00000080u) {
      x_ = from.x_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 32512u) {
    if (cached_has_bits & 0x00000100u) {
      y_ = from.y_;
    }
    if (cached_has_bits & 0x00000200u) {
      z_ = from.z_;
    }
    if (cached_has_bits & 0x00000400u) {
      q_x_ = from.q_x_;
    }
    if (cached_has_bits & 0x00000800u) {
      q_y_ = from.q_y_;
    }
    if (cached_has_bits & 0x00001000u) {
      q_z_ = from.q_z_;
    }
    if (cached_has_bits & 0x00002000u) {
      q_w_ = from.q_w_;
    }
    if (cached_has_bits & 0x00004000u) {
      height_ = from.height_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void OccupancyGrid::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto_msg.OccupancyGrid)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void OccupancyGrid::CopyFrom(const OccupancyGrid& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto_msg.OccupancyGrid)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OccupancyGrid::IsInitialized() const {
  if ((_has_bits_[0] & 0x00007fff) != 0x00007fff) return false;
  return true;
}

void OccupancyGrid::Swap(OccupancyGrid* other) {
  if (other == this) return;
  InternalSwap(other);
}
void OccupancyGrid::InternalSwap(OccupancyGrid* other) {
  using std::swap;
  protocol_type_.Swap(&other->protocol_type_);
  frame_id_.Swap(&other->frame_id_);
  map_data_.Swap(&other->map_data_);
  swap(publish_stamp_, other->publish_stamp_);
  swap(load_time_, other->load_time_);
  swap(resolution_, other->resolution_);
  swap(width_, other->width_);
  swap(x_, other->x_);
  swap(y_, other->y_);
  swap(z_, other->z_);
  swap(q_x_, other->q_x_);
  swap(q_y_, other->q_y_);
  swap(q_z_, other->q_z_);
  swap(q_w_, other->q_w_);
  swap(height_, other->height_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata OccupancyGrid::GetMetadata() const {
  protobuf_proto_5fmsgs_2eOccupancyGrid_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto_5fmsgs_2eOccupancyGrid_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// OccupancyGrid

// required string protocol_type = 1;
bool OccupancyGrid::has_protocol_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void OccupancyGrid::set_has_protocol_type() {
  _has_bits_[0] |= 0x00000001u;
}
void OccupancyGrid::clear_has_protocol_type() {
  _has_bits_[0] &= ~0x00000001u;
}
void OccupancyGrid::clear_protocol_type() {
  protocol_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_protocol_type();
}
const ::std::string& OccupancyGrid::protocol_type() const {
  // @@protoc_insertion_point(field_get:proto_msg.OccupancyGrid.protocol_type)
  return protocol_type_.GetNoArena();
}
void OccupancyGrid::set_protocol_type(const ::std::string& value) {
  set_has_protocol_type();
  protocol_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto_msg.OccupancyGrid.protocol_type)
}
#if LANG_CXX11
void OccupancyGrid::set_protocol_type(::std::string&& value) {
  set_has_protocol_type();
  protocol_type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto_msg.OccupancyGrid.protocol_type)
}
#endif
void OccupancyGrid::set_protocol_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_protocol_type();
  protocol_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto_msg.OccupancyGrid.protocol_type)
}
void OccupancyGrid::set_protocol_type(const char* value, size_t size) {
  set_has_protocol_type();
  protocol_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto_msg.OccupancyGrid.protocol_type)
}
::std::string* OccupancyGrid::mutable_protocol_type() {
  set_has_protocol_type();
  // @@protoc_insertion_point(field_mutable:proto_msg.OccupancyGrid.protocol_type)
  return protocol_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* OccupancyGrid::release_protocol_type() {
  // @@protoc_insertion_point(field_release:proto_msg.OccupancyGrid.protocol_type)
  clear_has_protocol_type();
  return protocol_type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void OccupancyGrid::set_allocated_protocol_type(::std::string* protocol_type) {
  if (protocol_type != NULL) {
    set_has_protocol_type();
  } else {
    clear_has_protocol_type();
  }
  protocol_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), protocol_type);
  // @@protoc_insertion_point(field_set_allocated:proto_msg.OccupancyGrid.protocol_type)
}

// required double publish_stamp = 2;
bool OccupancyGrid::has_publish_stamp() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void OccupancyGrid::set_has_publish_stamp() {
  _has_bits_[0] |= 0x00000008u;
}
void OccupancyGrid::clear_has_publish_stamp() {
  _has_bits_[0] &= ~0x00000008u;
}
void OccupancyGrid::clear_publish_stamp() {
  publish_stamp_ = 0;
  clear_has_publish_stamp();
}
double OccupancyGrid::publish_stamp() const {
  // @@protoc_insertion_point(field_get:proto_msg.OccupancyGrid.publish_stamp)
  return publish_stamp_;
}
void OccupancyGrid::set_publish_stamp(double value) {
  set_has_publish_stamp();
  publish_stamp_ = value;
  // @@protoc_insertion_point(field_set:proto_msg.OccupancyGrid.publish_stamp)
}

// required double load_time = 3;
bool OccupancyGrid::has_load_time() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void OccupancyGrid::set_has_load_time() {
  _has_bits_[0] |= 0x00000010u;
}
void OccupancyGrid::clear_has_load_time() {
  _has_bits_[0] &= ~0x00000010u;
}
void OccupancyGrid::clear_load_time() {
  load_time_ = 0;
  clear_has_load_time();
}
double OccupancyGrid::load_time() const {
  // @@protoc_insertion_point(field_get:proto_msg.OccupancyGrid.load_time)
  return load_time_;
}
void OccupancyGrid::set_load_time(double value) {
  set_has_load_time();
  load_time_ = value;
  // @@protoc_insertion_point(field_set:proto_msg.OccupancyGrid.load_time)
}

// required string frame_id = 4;
bool OccupancyGrid::has_frame_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void OccupancyGrid::set_has_frame_id() {
  _has_bits_[0] |= 0x00000002u;
}
void OccupancyGrid::clear_has_frame_id() {
  _has_bits_[0] &= ~0x00000002u;
}
void OccupancyGrid::clear_frame_id() {
  frame_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_frame_id();
}
const ::std::string& OccupancyGrid::frame_id() const {
  // @@protoc_insertion_point(field_get:proto_msg.OccupancyGrid.frame_id)
  return frame_id_.GetNoArena();
}
void OccupancyGrid::set_frame_id(const ::std::string& value) {
  set_has_frame_id();
  frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto_msg.OccupancyGrid.frame_id)
}
#if LANG_CXX11
void OccupancyGrid::set_frame_id(::std::string&& value) {
  set_has_frame_id();
  frame_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto_msg.OccupancyGrid.frame_id)
}
#endif
void OccupancyGrid::set_frame_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_frame_id();
  frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto_msg.OccupancyGrid.frame_id)
}
void OccupancyGrid::set_frame_id(const char* value, size_t size) {
  set_has_frame_id();
  frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto_msg.OccupancyGrid.frame_id)
}
::std::string* OccupancyGrid::mutable_frame_id() {
  set_has_frame_id();
  // @@protoc_insertion_point(field_mutable:proto_msg.OccupancyGrid.frame_id)
  return frame_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* OccupancyGrid::release_frame_id() {
  // @@protoc_insertion_point(field_release:proto_msg.OccupancyGrid.frame_id)
  clear_has_frame_id();
  return frame_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void OccupancyGrid::set_allocated_frame_id(::std::string* frame_id) {
  if (frame_id != NULL) {
    set_has_frame_id();
  } else {
    clear_has_frame_id();
  }
  frame_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), frame_id);
  // @@protoc_insertion_point(field_set_allocated:proto_msg.OccupancyGrid.frame_id)
}

// required float resolution = 5;
bool OccupancyGrid::has_resolution() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
void OccupancyGrid::set_has_resolution() {
  _has_bits_[0] |= 0x00000020u;
}
void OccupancyGrid::clear_has_resolution() {
  _has_bits_[0] &= ~0x00000020u;
}
void OccupancyGrid::clear_resolution() {
  resolution_ = 0;
  clear_has_resolution();
}
float OccupancyGrid::resolution() const {
  // @@protoc_insertion_point(field_get:proto_msg.OccupancyGrid.resolution)
  return resolution_;
}
void OccupancyGrid::set_resolution(float value) {
  set_has_resolution();
  resolution_ = value;
  // @@protoc_insertion_point(field_set:proto_msg.OccupancyGrid.resolution)
}

// required float width = 6;
bool OccupancyGrid::has_width() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
void OccupancyGrid::set_has_width() {
  _has_bits_[0] |= 0x00000040u;
}
void OccupancyGrid::clear_has_width() {
  _has_bits_[0] &= ~0x00000040u;
}
void OccupancyGrid::clear_width() {
  width_ = 0;
  clear_has_width();
}
float OccupancyGrid::width() const {
  // @@protoc_insertion_point(field_get:proto_msg.OccupancyGrid.width)
  return width_;
}
void OccupancyGrid::set_width(float value) {
  set_has_width();
  width_ = value;
  // @@protoc_insertion_point(field_set:proto_msg.OccupancyGrid.width)
}

// required float height = 7;
bool OccupancyGrid::has_height() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
void OccupancyGrid::set_has_height() {
  _has_bits_[0] |= 0x00004000u;
}
void OccupancyGrid::clear_has_height() {
  _has_bits_[0] &= ~0x00004000u;
}
void OccupancyGrid::clear_height() {
  height_ = 0;
  clear_has_height();
}
float OccupancyGrid::height() const {
  // @@protoc_insertion_point(field_get:proto_msg.OccupancyGrid.height)
  return height_;
}
void OccupancyGrid::set_height(float value) {
  set_has_height();
  height_ = value;
  // @@protoc_insertion_point(field_set:proto_msg.OccupancyGrid.height)
}

// required double x = 8;
bool OccupancyGrid::has_x() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
void OccupancyGrid::set_has_x() {
  _has_bits_[0] |= 0x00000080u;
}
void OccupancyGrid::clear_has_x() {
  _has_bits_[0] &= ~0x00000080u;
}
void OccupancyGrid::clear_x() {
  x_ = 0;
  clear_has_x();
}
double OccupancyGrid::x() const {
  // @@protoc_insertion_point(field_get:proto_msg.OccupancyGrid.x)
  return x_;
}
void OccupancyGrid::set_x(double value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:proto_msg.OccupancyGrid.x)
}

// required double y = 9;
bool OccupancyGrid::has_y() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
void OccupancyGrid::set_has_y() {
  _has_bits_[0] |= 0x00000100u;
}
void OccupancyGrid::clear_has_y() {
  _has_bits_[0] &= ~0x00000100u;
}
void OccupancyGrid::clear_y() {
  y_ = 0;
  clear_has_y();
}
double OccupancyGrid::y() const {
  // @@protoc_insertion_point(field_get:proto_msg.OccupancyGrid.y)
  return y_;
}
void OccupancyGrid::set_y(double value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:proto_msg.OccupancyGrid.y)
}

// required double z = 10;
bool OccupancyGrid::has_z() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
void OccupancyGrid::set_has_z() {
  _has_bits_[0] |= 0x00000200u;
}
void OccupancyGrid::clear_has_z() {
  _has_bits_[0] &= ~0x00000200u;
}
void OccupancyGrid::clear_z() {
  z_ = 0;
  clear_has_z();
}
double OccupancyGrid::z() const {
  // @@protoc_insertion_point(field_get:proto_msg.OccupancyGrid.z)
  return z_;
}
void OccupancyGrid::set_z(double value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:proto_msg.OccupancyGrid.z)
}

// required double q_x = 11;
bool OccupancyGrid::has_q_x() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
void OccupancyGrid::set_has_q_x() {
  _has_bits_[0] |= 0x00000400u;
}
void OccupancyGrid::clear_has_q_x() {
  _has_bits_[0] &= ~0x00000400u;
}
void OccupancyGrid::clear_q_x() {
  q_x_ = 0;
  clear_has_q_x();
}
double OccupancyGrid::q_x() const {
  // @@protoc_insertion_point(field_get:proto_msg.OccupancyGrid.q_x)
  return q_x_;
}
void OccupancyGrid::set_q_x(double value) {
  set_has_q_x();
  q_x_ = value;
  // @@protoc_insertion_point(field_set:proto_msg.OccupancyGrid.q_x)
}

// required double q_y = 12;
bool OccupancyGrid::has_q_y() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
void OccupancyGrid::set_has_q_y() {
  _has_bits_[0] |= 0x00000800u;
}
void OccupancyGrid::clear_has_q_y() {
  _has_bits_[0] &= ~0x00000800u;
}
void OccupancyGrid::clear_q_y() {
  q_y_ = 0;
  clear_has_q_y();
}
double OccupancyGrid::q_y() const {
  // @@protoc_insertion_point(field_get:proto_msg.OccupancyGrid.q_y)
  return q_y_;
}
void OccupancyGrid::set_q_y(double value) {
  set_has_q_y();
  q_y_ = value;
  // @@protoc_insertion_point(field_set:proto_msg.OccupancyGrid.q_y)
}

// required double q_z = 13;
bool OccupancyGrid::has_q_z() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
void OccupancyGrid::set_has_q_z() {
  _has_bits_[0] |= 0x00001000u;
}
void OccupancyGrid::clear_has_q_z() {
  _has_bits_[0] &= ~0x00001000u;
}
void OccupancyGrid::clear_q_z() {
  q_z_ = 0;
  clear_has_q_z();
}
double OccupancyGrid::q_z() const {
  // @@protoc_insertion_point(field_get:proto_msg.OccupancyGrid.q_z)
  return q_z_;
}
void OccupancyGrid::set_q_z(double value) {
  set_has_q_z();
  q_z_ = value;
  // @@protoc_insertion_point(field_set:proto_msg.OccupancyGrid.q_z)
}

// required double q_w = 14;
bool OccupancyGrid::has_q_w() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
void OccupancyGrid::set_has_q_w() {
  _has_bits_[0] |= 0x00002000u;
}
void OccupancyGrid::clear_has_q_w() {
  _has_bits_[0] &= ~0x00002000u;
}
void OccupancyGrid::clear_q_w() {
  q_w_ = 0;
  clear_has_q_w();
}
double OccupancyGrid::q_w() const {
  // @@protoc_insertion_point(field_get:proto_msg.OccupancyGrid.q_w)
  return q_w_;
}
void OccupancyGrid::set_q_w(double value) {
  set_has_q_w();
  q_w_ = value;
  // @@protoc_insertion_point(field_set:proto_msg.OccupancyGrid.q_w)
}

// required bytes map_data = 15;
bool OccupancyGrid::has_map_data() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void OccupancyGrid::set_has_map_data() {
  _has_bits_[0] |= 0x00000004u;
}
void OccupancyGrid::clear_has_map_data() {
  _has_bits_[0] &= ~0x00000004u;
}
void OccupancyGrid::clear_map_data() {
  map_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_map_data();
}
const ::std::string& OccupancyGrid::map_data() const {
  // @@protoc_insertion_point(field_get:proto_msg.OccupancyGrid.map_data)
  return map_data_.GetNoArena();
}
void OccupancyGrid::set_map_data(const ::std::string& value) {
  set_has_map_data();
  map_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto_msg.OccupancyGrid.map_data)
}
#if LANG_CXX11
void OccupancyGrid::set_map_data(::std::string&& value) {
  set_has_map_data();
  map_data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto_msg.OccupancyGrid.map_data)
}
#endif
void OccupancyGrid::set_map_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_map_data();
  map_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto_msg.OccupancyGrid.map_data)
}
void OccupancyGrid::set_map_data(const void* value, size_t size) {
  set_has_map_data();
  map_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto_msg.OccupancyGrid.map_data)
}
::std::string* OccupancyGrid::mutable_map_data() {
  set_has_map_data();
  // @@protoc_insertion_point(field_mutable:proto_msg.OccupancyGrid.map_data)
  return map_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* OccupancyGrid::release_map_data() {
  // @@protoc_insertion_point(field_release:proto_msg.OccupancyGrid.map_data)
  clear_has_map_data();
  return map_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void OccupancyGrid::set_allocated_map_data(::std::string* map_data) {
  if (map_data != NULL) {
    set_has_map_data();
  } else {
    clear_has_map_data();
  }
  map_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), map_data);
  // @@protoc_insertion_point(field_set_allocated:proto_msg.OccupancyGrid.map_data)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto_msg

// @@protoc_insertion_point(global_scope)
